# Generated by Django 5.2.1 on 2025-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_category_image_category_is_hot_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
