# Generated by Django 5.1.5 on 2025-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_sitesetting_facebook_sitesetting_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
