# Generated by Django 5.1.5 on 2025-11-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_sitesetting_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_description',
            field=models.TextField(blank=True, default='We are a creative and dedicated group of individuals who love web development.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_form_subtitle',
            field=models.CharField(blank=True, default='Your email address will not be published. Required fields are marked *', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_form_title',
            field=models.CharField(blank=True, default='Drop Us a Line', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact Me', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(blank=True, default='My Website', max_length=100),
        ),
    ]
