# Generated by Django 5.1.5 on 2025-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0007_sitesetting_contact_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hot_topics_description',
            field=models.TextField(blank=True, default="Don't miss the trending topics"),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hot_topics_title',
            field=models.CharField(blank=True, default='Hot topics', max_length=100),
        ),
    ]
