# Generated by Django 5.1.5 on 2025-11-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0008_sitesetting_hot_topics_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='banner_description',
            field=models.TextField(blank=True, default='I use animation as a third dimension by which to simplify experiences and guiding through each and every interaction.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner_greeting',
            field=models.CharField(blank=True, default='Hello Everyone!', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner_name',
            field=models.CharField(blank=True, default='Your Name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner_roles',
            field=models.CharField(blank=True, default='[ "Designer", "Developer", "Creator" ]', help_text='JSON format array for typewriter effect', max_length=255),
        ),
    ]
