# Generated by Django 5.1.5 on 2025-11-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_sitesetting_banner_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='subscribe_button_text',
            field=models.CharField(blank=True, default='Subscribe', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='subscribe_placeholder',
            field=models.CharField(blank=True, default='Type your email address', max_length=100),
        ),
    ]
