# Generated by Django 5.1.5 on 2025-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0010_subscriber_sitesetting_subscribe_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_description',
            field=models.TextField(blank=True, default='The convention is the main event of the year for professionals in the world of design and architecture.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_title',
            field=models.CharField(blank=True, default='My Latest Projects', max_length=200),
        ),
    ]
