# Generated by Django 5.1.5 on 2025-11-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0012_portfoliocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, help_text='Enter category name (e.g., Web Development, Mobile App, etc.)', max_length=100),
        ),
    ]
