# Generated by Django 5.1.5 on 2025-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0013_alter_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Technologies used (e.g., Django, React, PostgreSQL)', max_length=500),
        ),
    ]
