# Generated by Django 5.1.5 on 2025-11-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0014_portfolio_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_content_1',
            field=models.TextField(blank=True, default="I use animation as a third dimension by which to simplify experiences and guide you through each and every interaction. I'm not adding motion just to spruce things up, but doing it in ways that make your experience better."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_content_2',
            field=models.TextField(blank=True, default="On this blog, you'll find editor's picks, hot topics, and the latest posts from a variety of categories. Whether you're here for tips, reviews, or just to explore, I hope you enjoy your stay!"),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_intro',
            field=models.TextField(blank=True, default='Welcome to my blog! My name is Sakkhar, and I am passionate about sharing knowledge, ideas, and inspiration on technology, travel, lifestyle, and more.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(blank=True, default='About Me', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload resume PDF', null=True, upload_to='site_settings/'),
        ),
    ]
