# Generated by Django 5.1.5 on 2025-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0015_sitesetting_about_content_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='About Me', max_length=200)),
                ('intro', models.TextField(blank=True, default='Welcome to my blog! My name is Sakkhar, and I am passionate about sharing knowledge, ideas, and inspiration on technology, travel, lifestyle, and more.')),
                ('content_1', models.TextField(blank=True, default="I use animation as a third dimension by which to simplify experiences and guide you through each and every interaction. I'm not adding motion just to spruce things up, but doing it in ways that make your experience better.")),
                ('content_2', models.TextField(blank=True, default="On this blog, you'll find editor's picks, hot topics, and the latest posts from a variety of categories. Whether you're here for tips, reviews, or just to explore, I hope you enjoy your stay!")),
                ('resume_file', models.FileField(blank=True, help_text='Upload resume PDF', null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_content_1',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_content_2',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_intro',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='resume_file',
        ),
    ]
