# Generated by Django 5.1.5 on 2025-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0016_aboutpage_remove_sitesetting_about_content_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Contact Me', max_length=200)),
                ('description', models.TextField(blank=True, default='We are a creative and dedicated group of individuals who love web development.')),
                ('form_title', models.CharField(blank=True, default='Drop Us a Line', max_length=200)),
                ('form_subtitle', models.CharField(blank=True, default='Your email address will not be published. Required fields are marked *', max_length=255)),
                ('google_map_embed', models.TextField(blank=True, help_text='Google Maps embed URL')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_description',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_form_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_form_title',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_title',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='google_map_embed',
        ),
    ]
